import { createSlice, type PayloadAction } from '@reduxjs/toolkit'
import type { ContractTier } from '@/shared/types/contract'

// ── Types ─────────────────────────────────────────────────────────────────────

export type StudioPaperSize = 'letter' | 'a4' | 'legal'
export type StudioOrientation = 'portrait' | 'landscape'
export type StudioFontFamily = 'inter' | 'georgia' | 'times' | 'helvetica' | 'courier'
export type StudioFontSize = 'sm' | 'base' | 'lg'
export type StudioTab = 'editor' | 'layout'

export interface StudioLayout {
  paperSize: StudioPaperSize
  orientation: StudioOrientation
  margins: { top: number; right: number; bottom: number; left: number }
  header: string
  footer: string
  watermark: boolean
  watermarkText: string
}

export interface StudioStyles {
  fontFamily: StudioFontFamily
  fontSize: StudioFontSize
}

interface StudioState {
  /** The currently selected taxonomy contract type — drives which fields render in the left pane. */
  activeContractType: ContractTier | ''
  /** Per-field NOT AVAILABLE checkbox state, keyed by field identifier. */
  fieldNotAvailable: Record<string, boolean>
  studioTab: StudioTab
  layout: StudioLayout
  styles: StudioStyles
  finalized: boolean
}

// ── Defaults ──────────────────────────────────────────────────────────────────

const DEFAULT_LAYOUT: StudioLayout = {
  paperSize: 'letter',
  orientation: 'portrait',
  margins: { top: 1, right: 1, bottom: 1, left: 1 },
  header: 'Clearview Global, LLC',
  footer: 'Contract generated by Clearplan Command',
  watermark: false,
  watermarkText: 'DRAFT',
}

const DEFAULT_STYLES: StudioStyles = {
  fontFamily: 'inter',
  fontSize: 'base',
}

const initialState: StudioState = {
  activeContractType: '',
  fieldNotAvailable: {},
  studioTab: 'editor',
  layout: DEFAULT_LAYOUT,
  styles: DEFAULT_STYLES,
  finalized: false,
}

// ── Slice ─────────────────────────────────────────────────────────────────────

const studioSlice = createSlice({
  name: 'studio',
  initialState,
  reducers: {
    /** Dispatched when a taxonomy button is clicked in the action bar. Resets N/A states. */
    setActiveContractType(state, action: PayloadAction<ContractTier | ''>) {
      state.activeContractType = action.payload
      state.fieldNotAvailable = {}
    },

    /** Dispatched when a NOT AVAILABLE checkbox is toggled for a specific field. */
    setFieldNotAvailable(state, action: PayloadAction<{ key: string; value: boolean }>) {
      if (action.payload.value) {
        state.fieldNotAvailable[action.payload.key] = true
      } else {
        delete state.fieldNotAvailable[action.payload.key]
      }
    },

    setStudioTab(state, action: PayloadAction<StudioTab>) {
      state.studioTab = action.payload
    },

    patchLayout(state, action: PayloadAction<Partial<Omit<StudioLayout, 'margins'>>>) {
      Object.assign(state.layout, action.payload)
    },

    patchLayoutMargins(
      state,
      action: PayloadAction<Partial<StudioLayout['margins']>>,
    ) {
      Object.assign(state.layout.margins, action.payload)
    },

    patchStyles(state, action: PayloadAction<Partial<StudioStyles>>) {
      Object.assign(state.styles, action.payload)
    },

    setFinalized(state, action: PayloadAction<boolean>) {
      state.finalized = action.payload
    },

    resetStudio() {
      return { ...initialState }
    },
  },
})

export const {
  setActiveContractType,
  setFieldNotAvailable,
  setStudioTab,
  patchLayout,
  patchLayoutMargins,
  patchStyles,
  setFinalized,
  resetStudio,
} = studioSlice.actions

export default studioSlice.reducer
