import {
  Bell,
  BarChart3,
  Bot,
  BriefcaseBusiness,
  CalendarCheck,
  CalendarDays,
  CheckSquare,
  ContactRound,
  FileSignature,
  Files,
  FolderKanban,
  Handshake,
  LayoutTemplate,
  LogIn,
  Map,
  Plug,
  ReceiptText,
  Settings,
  Tags,
  Users
} from "lucide-react";

export const navItems = [
  { label: "Dashboard", path: "/dashboard", icon: BarChart3 },
  { label: "Projects", path: "/projects", icon: FolderKanban },
  { label: "Contracts", path: "/contracts", icon: FileSignature },
  { label: "Quotes", path: "/quotes", icon: ReceiptText },
  { label: "Customers", path: "/customers", icon: ContactRound },
  { label: "CRM", path: "/crm", icon: Handshake },
  { label: "Documents", path: "/documents", icon: Files },
  { label: "Calendar", path: "/calendar", icon: CalendarDays },
  { label: "Notifications", path: "/notifications", icon: Bell },
  { label: "AI Hub", path: "/ai-hub", icon: Bot },
  { label: "Integrations", path: "/integrations", icon: Plug },
  { label: "Settings", path: "/settings", icon: Settings },
  { label: "Map", path: "/map", icon: Map },
  { label: "Timesheets", path: "/clock/timesheets", icon: CalendarCheck },
  { label: "Employees", path: "/employees", icon: Users },
  { label: "Templates", path: "/templates", icon: LayoutTemplate },
  { label: "Checklists", path: "/checklists", icon: CheckSquare },
  { label: "Categories", path: "/categories", icon: Tags },
  { label: "Users", path: "/users", icon: BriefcaseBusiness },
  { label: "Account", path: "/account", icon: Settings },
  { label: "Mobile", path: "/mobile", icon: LogIn }
];
